version: 2
jobs:
  build:
    working_directory: ~/circle-tmp-folder
    steps:
      ... # build/dependancies
      - run:
          name: build
          command: 'npm build'

  deploy:
    machine:
      enabled: true
    working_directory: ~/circle-tmp-folder
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ${source}/ s3://gastarme-public --region us-east-1'