version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/circle-tmp-folder
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install aws cli
          command:
              sudo apt-get -y -qq install awscli
              
      - run:
          name: Install Angular
          command: |
            #sudo npm i -g serverless
            npm install
            npm build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Deploy
          command: 'aws s3 sync dist/ s3://gastarme-public --region us-east-1'
